projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-1
        apiId: mkre4vw4ebblxhou333n7d6d3m
        frontend: ios
        maxDepth: 2
extensions:
  amplify:
    version: 3
