# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AreveaTV' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for AreveaTV
 use_frameworks!
  pod 'AWSCore'
  pod 'AWSMobileClient'
  pod 'AWSCognito'
  pod 'AWSFacebookSignIn'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSAuthUI'
  pod ‘Alamofire’
pod 'MaterialComponents'
pod 'SendBirdSDK'
pod 'Mux-Stats-AVPlayer', '~>1.3.0'
pod 'AWSAPIGateway'
pod "AGEmojiKeyboard"
pod 'AWSAppSync'
pod 'EasyTipView', '~> 2.0.4'


end
