# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AreveaTV' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for AreveaTV
 use_frameworks!
  pod 'KeychainAccess'
  pod 'IQKeyboardManagerSwift'
  pod 'AWSCore', '~> 2.9.0'
  pod 'AWSMobileClient', '~> 2.9.0'
  pod 'Instabug'
pod ‘Alamofire’
end
